# typed: false
# frozen_string_literal: true

# Homebrew formula for bino CLI
# This file is auto-generated by CI. Do not edit manually.
class BinoCli < Formula
  desc "CLI tool for building pixel-perfect PDF reports from YAML manifests and SQL queries"
  homepage "https://cli.bino.bi"
  license "BSAL"
  version "0.52.13"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/bino-bi/bino-cli-releases/releases/download/v0.52.13/bino-cli_Darwin_arm64.tar.gz"
      sha256 "35e411e6c162c28bd415b26891d2753ce413e3cd86be2d7bef1db301602ae5da"
    else
      url "https://github.com/bino-bi/bino-cli-releases/releases/download/v0.52.13/bino-cli_Darwin_x86_64.tar.gz"
      sha256 "8457d2fd035359ddde06d11c780f6f130663e4272bb99b5cc644e228e50bbcbb"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/bino-bi/bino-cli-releases/releases/download/v0.52.13/bino-cli_Linux_x86_64.tar.gz"
      sha256 "08cd63dfa4d00b0ff22dc1673c7d73698c6f6c8d55a38412348e4c843f01fe17"
    end
  end

  def install
    bin.install "bino"
  end

  def caveats
    <<~EOS
      To complete the installation, run:
        bino setup

      This downloads the browser runtime required for PDF rendering.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/bino version")
  end
end
