# typed: false
# frozen_string_literal: true

# Homebrew formula for bino CLI
# This file is auto-generated by CI. Do not edit manually.
class BinoCli < Formula
  desc "CLI tool for building pixel-perfect PDF reports from YAML manifests and SQL queries"
  homepage "https://cli.bino.bi"
  license "BSAL"
  version "0.60.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/bino-bi/bino-cli-releases/releases/download/v0.60.3/bino-cli_Darwin_arm64.tar.gz"
      sha256 "e4a9bf16715b585ebbe00f3f191d134aa822ddf5392aa10343c864a4683c4c3a"
    else
      url "https://github.com/bino-bi/bino-cli-releases/releases/download/v0.60.3/bino-cli_Darwin_x86_64.tar.gz"
      sha256 "64a7920935f25561915cca424637b781cb5fcf992c20b28af16dc8591bed7648"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/bino-bi/bino-cli-releases/releases/download/v0.60.3/bino-cli_Linux_x86_64.tar.gz"
      sha256 "861afd07ec7c0407241875dbef804e936c1e2b3a978f1e4820d52b3a73cd7970"
    end
  end

  def install
    bin.install "bino"
  end

  def caveats
    <<~EOS
      To complete the installation, run:
        bino setup

      This downloads the browser runtime required for PDF rendering.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/bino version")
  end
end
