# typed: false
# frozen_string_literal: true

# Homebrew formula for bino CLI
# This file is auto-generated by CI. Do not edit manually.
class Bino < Formula
  desc "CLI tool for building pixel-perfect PDF reports from YAML manifests and SQL queries"
  homepage "https://cli.bino.bi"
  license "BSAL"
  version "0.44.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/bino-bi/bino-cli-releases/releases/download/v0.44.0/bino-cli_Darwin_arm64.tar.gz"
      sha256 "42f99708bbf9248f4ccf438caad4ef5a10d048ad55389f333802a6c13736ffe0"
    else
      url "https://github.com/bino-bi/bino-cli-releases/releases/download/v0.44.0/bino-cli_Darwin_x86_64.tar.gz"
      sha256 "34f9c32dd654b84fb6585ccb849a259d40736567d20f43efd62bd19e6b64bc6b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/bino-bi/bino-cli-releases/releases/download/v0.44.0/bino-cli_Linux_x86_64.tar.gz"
      sha256 "f8028950ed55fb7cd14e0baacef838859ed12b29903aab0c44fe550cb00489d2"
    end
  end

  def install
    bin.install "bino"
  end

  def post_install
    system "#{bin}/bino", "setup"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/bino version")
  end
end
